"""add transaction table

Revision ID: 43704b57dcd9
Revises: 38364d45205b
Create Date: 2023-03-05 04:49:08.460267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43704b57dcd9'
down_revision = '38364d45205b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
