"""add role Columns

Revision ID: 9311c6bfa98e
Revises: 2d3ab766dcd6
Create Date: 2023-02-21 12:58:04.739345

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9311c6bfa98e"
down_revision = "2d3ab766dcd6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = postgresql.ENUM("super_admin", "admin", "user", name="userrole")
    user_role.create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "role", sa.Enum("super_admin", "admin", "user", name="userrole"), server_default="user", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
